import { TaskPriorities, TaskStatuses } from 'common/emuns'
import { Tasks } from 'common/types'

export const tasksInitial: Tasks = {
  ['todoListId1']: [
    {
      id: 'todoListId1',
      title: 'HTML&CSS',
      description: '',
      completed: false,
      status: TaskStatuses.Completed,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId1',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId1',
      title: 'JS',
      description: '',
      completed: false,
      status: TaskStatuses.Completed,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId1',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId1',
      title: 'ReactJS',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId1',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId1',
      title: 'Rest API',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId1',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId1',
      title: 'GraphQL',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId1',
      order: 1,
      addedDate: '',
    },
  ],
  ['todoListId2']: [
    {
      id: 'todoListId2',
      title: 'Milk',
      description: '',
      completed: true,
      status: TaskStatuses.Completed,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId2',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId2',
      title: 'Water',
      description: '',
      completed: true,
      status: TaskStatuses.Completed,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId2',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId2',
      title: 'Juice',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId2',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId2',
      title: 'Fish',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId2',
      order: 1,
      addedDate: '',
    },
    {
      id: 'todoListId2',
      title: 'Eggs',
      description: '',
      completed: false,
      status: TaskStatuses.New,
      priority: TaskPriorities.Low,
      startDate: '',
      deadline: '',
      todoListId: 'todoListId2',
      order: 1,
      addedDate: '',
    },
  ],
}
